version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mamamia1
      MYSQL_DATABASE: habittracker
      MYSQL_USER: habituser
      MYSQL_PASSWORD: mamamia1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf 

volumes:
  mysql-data: